/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_mfaVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_mfaStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_mfaSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_mfaEnable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_mfaDisable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientesController_list"];
        put?: never;
        post: operations["ClientesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientesController_ficha"];
        put?: never;
        post?: never;
        delete: operations["ClientesController_removeCliente"];
        options?: never;
        head?: never;
        patch: operations["ClientesController_updateCliente"];
        trace?: never;
    };
    "/api/clientes/{id}/animais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClientesController_addAnimal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animais/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientesController_animal"];
        put?: never;
        post?: never;
        delete: operations["ClientesController_removeAnimal"];
        options?: never;
        head?: never;
        patch: operations["ClientesController_updateAnimal"];
        trace?: never;
    };
    "/api/animais/{id}/foto/sign-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClientesController_signFoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animais/{id}/foto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClientesController_confirmFoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animais/{id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProntuarioController_eventos"];
        put?: never;
        post: operations["ProntuarioController_addEvento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/animais/{id}/prontuario/sign-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProntuarioController_signAnexo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clientes/{id}/fatura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProntuarioController_fatura"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FinanceiroController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faturas/{id}/pagar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FinanceiroController_pagar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/faturas/{id}/recebimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FinanceiroController_recebimentos"];
        put?: never;
        post: operations["FinanceiroController_receber"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financeiro/saldos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FinanceiroController_saldos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financeiro/saldos/{responsavelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FinanceiroController_saldoDe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/formas-recebimento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FinanceiroController_formas"];
        put?: never;
        post: operations["FinanceiroController_createForma"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/formas-recebimento/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FinanceiroController_updateForma"];
        trace?: never;
    };
    "/api/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgendaController_list"];
        put?: never;
        post: operations["AgendaController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/profissionais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgendaController_profissionais"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/tipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgendaController_tipos"];
        put?: never;
        post: operations["AgendaController_createTipo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/tipos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AgendaController_updateTipo"];
        trace?: never;
    };
    "/api/agenda/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AgendaController_updateStatus"];
        trace?: never;
    };
    "/api/agenda/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AgendaController_cancelar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogoController_list"];
        put?: never;
        post: operations["CatalogoController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogo/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CatalogoController_remove"];
        options?: never;
        head?: never;
        patch: operations["CatalogoController_update"];
        trace?: never;
    };
    "/api/estoque": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EstoqueController_saldos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estoque/{itemId}/movimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EstoqueController_movimentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estoque/movimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EstoqueController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estoque/{itemId}/minimo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["EstoqueController_minimo"];
        trace?: never;
    };
    "/api/internacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InternacaoController_list"];
        put?: never;
        post: operations["InternacaoController_admitir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internacoes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InternacaoController_detalhe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internacoes/{id}/execucoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternacaoController_prescrever"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internacoes/{id}/execucoes/{execId}/executar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternacaoController_executar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internacoes/{id}/alta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternacaoController_alta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VendasController_list"];
        put?: never;
        post: operations["VendasController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VendasController_detalhe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos/{id}/itens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["VendasController_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos/{id}/itens/{linhaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["VendasController_removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orcamentos/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["VendasController_updateStatus"];
        trace?: never;
    };
    "/api/orcamentos/{id}/converter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["VendasController_converter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comissoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComissoesController_apurar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comissoes/minhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComissoesController_minhas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comissoes/regras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComissoesController_regras"];
        put?: never;
        post: operations["ComissoesController_upsertRegra"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comissoes/regras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ComissoesController_removeRegra"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_resumo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inteligencia/produtividade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InteligenciaController_produtividade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example Clínica Cuidar */
            tenantName: string;
            /** @example dono@clinica.com */
            email: string;
            /** @example Maria Dona */
            name: string;
            /** @example senha-forte-aqui */
            password: string;
        };
        TokensDto: {
            accessToken: string;
            refreshToken: string;
        };
        LoginDto: {
            /** @example dono@clinica.com */
            email: string;
            /** @example senha-forte-aqui */
            password: string;
            /** @description Tenant ativo (quando o usuário pertence a mais de um) */
            tenantId?: string;
        };
        LoginResultDto: {
            accessToken?: string;
            refreshToken?: string;
            mfaRequired?: boolean;
            /** @description Token temporário para concluir o MFA */
            mfaToken?: string;
        };
        GoogleLoginDto: {
            /** @description id_token retornado pelo Google Identity Services */
            idToken: string;
        };
        MfaVerifyDto: {
            /** @description mfaToken devolvido pelo login */
            mfaToken: string;
            /**
             * @description Código TOTP do autenticador
             * @example 123456
             */
            code: string;
        };
        MfaStatusDto: {
            enabled: boolean;
        };
        MfaSetupResponseDto: {
            /** @description Segredo TOTP (base32) — exibir uma única vez */
            secret: string;
            /** @description URL otpauth:// para QR code */
            otpauthUrl: string;
        };
        MfaCodeDto: {
            /** @example 123456 */
            code: string;
        };
        OkResponseDto: {
            ok: boolean;
        };
        AuthMeDto: {
            userId: string;
            tenantId: string;
            /** @example admin */
            role: string;
        };
        ResponsavelDto: {
            id: string;
            codigo?: string;
            nome: string;
            email?: string;
            telefone?: string;
            documento?: string;
            origem?: string;
        };
        ListResponsaveisDto: {
            items: components["schemas"]["ResponsavelDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateResponsavelDto: {
            /** @example Maria Silva */
            nome: string;
            codigo?: string;
            /** @example maria@email.com */
            email?: string;
            /** @example +55 11 99999-0000 */
            telefone?: string;
            documento?: string;
            /** @description Como nos conheceu? */
            origem?: string;
        };
        AnimalDto: {
            id: string;
            responsavelId: string;
            codigo?: string;
            nome: string;
            especie?: string;
            raca?: string;
            sexo?: string;
            castrado: boolean;
            nascimento?: string;
            status: string;
            /** @description URL assinada (curta) da foto, se houver */
            fotoUrl?: string;
        };
        ResponsavelComAnimaisDto: {
            id: string;
            codigo?: string;
            nome: string;
            email?: string;
            telefone?: string;
            documento?: string;
            origem?: string;
            animais: components["schemas"]["AnimalDto"][];
        };
        UpdateResponsavelDto: {
            nome?: string;
            codigo?: string;
            email?: string;
            telefone?: string;
            documento?: string;
            origem?: string;
        };
        OkDto: {
            ok: boolean;
        };
        CreateAnimalDto: {
            /** @example Rex */
            nome: string;
            codigo?: string;
            /** @example Canina */
            especie?: string;
            /** @example Labrador */
            raca?: string;
            /** @enum {string} */
            sexo?: "M" | "F";
            castrado?: boolean;
            /**
             * @description AAAA-MM-DD
             * @example 2020-05-10
             */
            nascimento?: string;
        };
        UpdateAnimalDto: {
            nome?: string;
            codigo?: string;
            especie?: string;
            raca?: string;
            /** @enum {string} */
            sexo?: "M" | "F";
            castrado?: boolean;
            nascimento?: string;
            /** @enum {string} */
            status?: "vivo" | "falecido";
        };
        SignUploadDto: {
            /**
             * @example image/jpeg
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png" | "image/webp";
        };
        SignUploadResponseDto: {
            key: string;
            uploadUrl: string;
        };
        ConfirmFotoDto: {
            key: string;
        };
        EventoDto: {
            id: string;
            animalId: string;
            tipo: string;
            descricao: string;
            valorCentavos?: number;
            data: string;
            /** @description URL assinada (curta) do anexo, se houver */
            anexoUrl?: string;
        };
        CreateEventoDto: {
            /** @enum {string} */
            tipo: "atendimento" | "peso" | "vacina" | "exame" | "receita" | "observacao" | "internacao";
            /** @example Consulta clínica de rotina */
            descricao: string;
            /** @description Valor em centavos (ex.: 15000 = R$ 150,00) */
            valorCentavos?: number;
            /**
             * @description Gera lançamento na fatura do cliente
             * @default true
             */
            faturar: boolean;
            /** @description Chave de anexo já enviado ao storage (opcional) */
            anexoKey?: string;
        };
        ProntuarioSignUploadDto: {
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp" | "application/pdf" | "video/mp4";
        };
        FaturaItemDto: {
            id: string;
            descricao: string;
            valorCentavos: number;
            eventoId?: string;
        };
        FaturaDto: {
            id: string;
            responsavelId: string;
            status: string;
            totalCentavos: number;
            itens: components["schemas"]["FaturaItemDto"][];
        };
        FaturaResumoDto: {
            id: string;
            responsavelId: string;
            responsavelNome: string;
            status: string;
            totalCentavos: number;
            /** @description Total já recebido (soma dos recebimentos) */
            recebidoCentavos: number;
            itens: number;
            criadaEm: string;
        };
        ReceberDto: {
            /** @description Valor recebido em centavos (≤ saldo em aberto) */
            valorCentavos: number;
            /** @description Forma de recebimento */
            formaId?: string;
            observacao?: string;
        };
        ReceberResultDto: {
            ok: boolean;
            status: string;
            recebidoCentavos: number;
            saldoCentavos: number;
        };
        RecebimentoDto: {
            id: string;
            valorCentavos: number;
            formaId: string | null;
            formaNome: string | null;
            observacao: string | null;
            criadoEm: string;
        };
        SaldoClienteDto: {
            responsavelId: string;
            responsavelNome: string;
            /** @description Saldo devedor em aberto (centavos) */
            devedorCentavos: number;
            faturasAbertas: number;
        };
        FormaRecebimentoDto: {
            id: string;
            nome: string;
            tipo: string;
            taxaBps: number;
            ativo: boolean;
        };
        CreateFormaDto: {
            /** @example Pix */
            nome: string;
            /** @enum {string} */
            tipo: "dinheiro" | "pix" | "cartao_credito" | "cartao_debito" | "transferencia" | "outro";
            /**
             * @description Taxa em basis points (2,5% = 250)
             * @example 0
             */
            taxaBps?: number;
        };
        UpdateFormaDto: {
            nome?: string;
            taxaBps?: number;
            ativo?: boolean;
        };
        AgendamentoDto: {
            id: string;
            titulo: string;
            inicio: string;
            fim: string;
            status: string;
            tipoAtendimentoId?: string;
            tipoNome?: string;
            cor?: string;
            profissionalId?: string;
            profissionalNome?: string;
            animalId?: string;
            responsavelId?: string;
            observacoes?: string;
        };
        CreateAgendamentoDto: {
            /** @example Consulta — Rex */
            titulo: string;
            /**
             * @description ISO 8601
             * @example 2026-07-01T14:00:00Z
             */
            inicio: string;
            /**
             * @description ISO 8601. Opcional com tipoAtendimentoId (usa a duração do tipo).
             * @example 2026-07-01T14:30:00Z
             */
            fim?: string;
            /** @description Tipo de atendimento (define duração/cor) */
            tipoAtendimentoId?: string;
            /** @description Profissional responsável (membro do tenant) */
            profissionalId?: string;
            animalId?: string;
            responsavelId?: string;
            observacoes?: string;
        };
        ProfissionalDto: {
            userId: string;
            nome: string;
            role: string;
        };
        TipoAtendimentoDto: {
            id: string;
            nome: string;
            duracaoMinutos: number;
            cor: string | null;
            ativo: boolean;
        };
        CreateTipoAtendimentoDto: {
            /** @example Consulta */
            nome: string;
            /**
             * @description Duração padrão em minutos
             * @example 30
             */
            duracaoMinutos?: number;
            /**
             * @description Cor do evento na agenda (hex)
             * @example #7c5cff
             */
            cor?: string;
        };
        UpdateTipoAtendimentoDto: {
            /** @example Consulta */
            nome?: string;
            duracaoMinutos?: number;
            /** @example #7c5cff */
            cor?: string;
            ativo?: boolean;
        };
        UpdateStatusDto: {
            /** @enum {string} */
            status: "agendado" | "confirmado" | "concluido" | "faltou" | "cancelado";
        };
        ItemCatalogoDto: {
            id: string;
            codigo: string;
            nome: string;
            tipo: string;
            precoCentavos: number;
            ativo: boolean;
        };
        CreateItemDto: {
            /**
             * @description Código único do item no tenant
             * @example 22
             */
            codigo: string;
            /** @example Avaliação cirúrgica */
            nome: string;
            /** @enum {string} */
            tipo: "produto" | "servico" | "exame" | "vacina" | "medicamento" | "cirurgia";
            /**
             * @description Preço em centavos
             * @example 15000
             */
            precoCentavos: number;
        };
        UpdateItemDto: {
            codigo?: string;
            nome?: string;
            /** @enum {string} */
            tipo?: "produto" | "servico" | "exame" | "vacina" | "medicamento" | "cirurgia";
            precoCentavos?: number;
            ativo?: boolean;
        };
        SaldoItemDto: {
            itemId: string;
            codigo: string;
            nome: string;
            tipo: string;
            saldo: number;
            estoqueMinimo: number;
            abaixoDoMinimo: boolean;
        };
        MovimentoDto: {
            id: string;
            itemId: string;
            tipo: string;
            quantidade: number;
            custoCentavos: number | null;
            motivo: string | null;
            criadoEm: string;
        };
        CreateMovimentoDto: {
            /** @description Item do catálogo (estocável) */
            itemId: string;
            /** @enum {string} */
            tipo: "entrada" | "saida" | "ajuste";
            /**
             * @description Quantidade. entrada/saida: magnitude positiva; ajuste: delta com sinal (inventário).
             * @example 10
             */
            quantidade: number;
            /** @description Custo unitário em centavos (entrada) */
            custoCentavos?: number;
            /** @description Observação (NF, fornecedor, motivo do ajuste) */
            motivo?: string;
        };
        MovimentoResultDto: {
            id: string;
            itemId: string;
            tipo: string;
            quantidade: number;
            custoCentavos: number | null;
            motivo: string | null;
            criadoEm: string;
            /** @description Saldo do item após a movimentação */
            saldoAtual: number;
        };
        SetMinimoDto: {
            /** @example 5 */
            estoqueMinimo: number;
        };
        InternacaoResumoDto: {
            id: string;
            animalId: string;
            animalNome: string;
            responsavelId: string;
            responsavelNome: string;
            motivo: string;
            box: string | null;
            status: string;
            entradaEm: string;
            altaEm: string | null;
            /** @description Prescrições ainda não executadas */
            pendentes: number;
        };
        AdmitirDto: {
            /** @description Animal a internar */
            animalId: string;
            /** @example Pós-operatório de castração */
            motivo: string;
            /** @example Box 2 */
            box?: string;
        };
        ExecucaoDto: {
            id: string;
            itemId: string | null;
            descricao: string;
            quantidade: number;
            valorCentavos: number | null;
            executadaEm: string | null;
        };
        InternacaoDetalheDto: {
            id: string;
            animalId: string;
            animalNome: string;
            responsavelId: string;
            responsavelNome: string;
            motivo: string;
            box: string | null;
            status: string;
            entradaEm: string;
            altaEm: string | null;
            /** @description Prescrições ainda não executadas */
            pendentes: number;
            observacoes: string | null;
            execucoes: components["schemas"]["ExecucaoDto"][];
        };
        PrescreverDto: {
            /** @description Item do catálogo (medicamento/procedimento) */
            itemId?: string;
            /**
             * @description Descrição livre (obrigatória sem itemId)
             * @example Dipirona 25mg/kg IV
             */
            descricao?: string;
            /**
             * @description Quantidade (baixa de estoque por execução)
             * @example 1
             */
            quantidade?: number;
            /** @description Valor unitário em centavos; default = preço do catálogo */
            valorCentavos?: number;
        };
        ExecutarResultDto: {
            id: string;
            itemId: string | null;
            descricao: string;
            quantidade: number;
            valorCentavos: number | null;
            executadaEm: string | null;
            /** @description false quando não havia saldo em estoque (execução registrada mesmo assim) */
            estoqueBaixado: boolean;
            /** @description true quando o valor foi lançado na fatura aberta */
            faturado: boolean;
        };
        AltaDto: {
            /** @example Alta com retorno em 7 dias */
            observacoes?: string;
        };
        OrcamentoResumoDto: {
            id: string;
            responsavelId: string;
            responsavelNome: string;
            status: string;
            totalCentavos: number;
            itens: number;
            observacoes: string | null;
            criadoEm: string;
        };
        CreateOrcamentoDto: {
            /** @description Responsável (cliente) do orçamento */
            responsavelId: string;
            /** @example Pacote pós-cirúrgico */
            observacoes?: string;
        };
        OrcamentoItemDto: {
            id: string;
            itemId: string | null;
            descricao: string;
            quantidade: number;
            valorCentavos: number;
        };
        OrcamentoDetalheDto: {
            id: string;
            responsavelId: string;
            responsavelNome: string;
            status: string;
            totalCentavos: number;
            itens: number;
            observacoes: string | null;
            criadoEm: string;
            linhas: components["schemas"]["OrcamentoItemDto"][];
        };
        AddOrcamentoItemDto: {
            /** @description Item do catálogo (herda nome/preço) */
            itemId?: string;
            /** @description Descrição livre (obrigatória sem itemId) */
            descricao?: string;
            /** @example 1 */
            quantidade?: number;
            /** @description Valor unitário em centavos; default = preço do catálogo */
            valorCentavos?: number;
        };
        UpdateOrcamentoStatusDto: {
            /** @enum {string} */
            status: "aprovado" | "recusado";
        };
        ConverterResultDto: {
            ok: boolean;
            /** @description Total lançado na fatura aberta (centavos) */
            totalCentavos: number;
        };
        ApuracaoColaboradorDto: {
            userId: string;
            nome: string;
            /** @description Base comissionável no período (centavos) */
            baseCentavos: number;
            /** @description Comissão apurada no período (centavos) */
            comissaoCentavos: number;
            lancamentos: number;
        };
        ApuracaoLinhaDto: {
            descricao: string;
            valorCentavos: number;
            percentBps: number;
            comissaoCentavos: number;
            criadoEm: string;
        };
        RegraDto: {
            id: string;
            userId: string;
            userNome: string;
            itemId: string | null;
            itemNome: string | null;
            percentBps: number;
        };
        CreateRegraDto: {
            /** @description Colaborador (membro do tenant) */
            userId: string;
            /** @description Item do catálogo; ausente = regra geral do colaborador */
            itemId?: string;
            /**
             * @description Percentual em basis points (10% = 1000)
             * @example 1000
             */
            percentBps: number;
        };
        ProximoAgendamentoDto: {
            id: string;
            titulo: string;
            inicio: string;
            profissionalNome: string | null;
            cor: string | null;
        };
        DashboardDto: {
            agendamentosHoje: number;
            minhaAgendaHoje: number;
            proximos: components["schemas"]["ProximoAgendamentoDto"][];
            internados: number;
            execucoesPendentes: number;
            faturasAbertas: number;
            faturasAbertasCentavos: number;
            receitaMesCentavos: number;
            estoqueAbaixoMinimo: number;
            orcamentosAbertos: number;
            clientes: number;
            minhasComissoesMesCentavos: number;
        };
        ProdutividadeDto: {
            userId: string;
            nome: string;
            /** @description Lançamentos faturados atribuídos ao colaborador */
            lancamentos: number;
            /** @description Receita gerada (centavos) */
            receitaCentavos: number;
            /** @description Agendamentos concluídos no período */
            agendamentosConcluidos: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResultDto"];
                };
            };
        };
    };
    AuthController_google: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResultDto"];
                };
            };
        };
    };
    AuthController_mfaVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_mfaStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusDto"];
                };
            };
        };
    };
    AuthController_mfaSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetupResponseDto"];
                };
            };
        };
    };
    AuthController_mfaEnable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    AuthController_mfaDisable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeDto"];
                };
            };
        };
    };
    ClientesController_list: {
        parameters: {
            query?: {
                /** @description Nome ou telefone */
                search?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponsaveisDto"];
                };
            };
        };
    };
    ClientesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResponsavelDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsavelDto"];
                };
            };
        };
    };
    ClientesController_ficha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsavelComAnimaisDto"];
                };
            };
        };
    };
    ClientesController_removeCliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkDto"];
                };
            };
        };
    };
    ClientesController_updateCliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResponsavelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsavelDto"];
                };
            };
        };
    };
    ClientesController_addAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnimalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    ClientesController_animal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    ClientesController_removeAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkDto"];
                };
            };
        };
    };
    ClientesController_updateAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAnimalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    ClientesController_signFoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUploadResponseDto"];
                };
            };
        };
    };
    ClientesController_confirmFoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmFotoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    ProntuarioController_eventos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoDto"][];
                };
            };
        };
    };
    ProntuarioController_addEvento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoDto"];
                };
            };
        };
    };
    ProntuarioController_signAnexo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProntuarioSignUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUploadResponseDto"];
                };
            };
        };
    };
    ProntuarioController_fatura: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaturaDto"];
                };
            };
        };
    };
    FinanceiroController_list: {
        parameters: {
            query?: {
                status?: "aberta" | "parcial" | "paga" | "cancelada";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaturaResumoDto"][];
                };
            };
        };
    };
    FinanceiroController_pagar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkDto"];
                };
            };
        };
    };
    FinanceiroController_recebimentos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecebimentoDto"][];
                };
            };
        };
    };
    FinanceiroController_receber: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceberResultDto"];
                };
            };
        };
    };
    FinanceiroController_saldos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaldoClienteDto"][];
                };
            };
        };
    };
    FinanceiroController_saldoDe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                responsavelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaldoClienteDto"];
                };
            };
        };
    };
    FinanceiroController_formas: {
        parameters: {
            query?: {
                incluirInativos?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormaRecebimentoDto"][];
                };
            };
        };
    };
    FinanceiroController_createForma: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFormaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormaRecebimentoDto"];
                };
            };
        };
    };
    FinanceiroController_updateForma: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFormaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormaRecebimentoDto"];
                };
            };
        };
    };
    AgendaController_list: {
        parameters: {
            query?: {
                /** @description ISO 8601 */
                from?: string;
                /** @description ISO 8601 */
                to?: string;
                /** @description Filtra por profissional ("minha agenda") */
                profissionalId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendamentoDto"][];
                };
            };
        };
    };
    AgendaController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgendamentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendamentoDto"];
                };
            };
        };
    };
    AgendaController_profissionais: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfissionalDto"][];
                };
            };
        };
    };
    AgendaController_tipos: {
        parameters: {
            query?: {
                incluirInativos?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoAtendimentoDto"][];
                };
            };
        };
    };
    AgendaController_createTipo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTipoAtendimentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoAtendimentoDto"];
                };
            };
        };
    };
    AgendaController_updateTipo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTipoAtendimentoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoAtendimentoDto"];
                };
            };
        };
    };
    AgendaController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    AgendaController_cancelar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    CatalogoController_list: {
        parameters: {
            query?: {
                /** @description Nome ou código */
                search?: string;
                tipo?: string;
                incluirInativos?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemCatalogoDto"][];
                };
            };
        };
    };
    CatalogoController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemCatalogoDto"];
                };
            };
        };
    };
    CatalogoController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    CatalogoController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemCatalogoDto"];
                };
            };
        };
    };
    EstoqueController_saldos: {
        parameters: {
            query?: {
                /** @description Nome ou código */
                search?: string;
                /** @description Só itens abaixo do mínimo */
                apenasBaixo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaldoItemDto"][];
                };
            };
        };
    };
    EstoqueController_movimentos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimentoDto"][];
                };
            };
        };
    };
    EstoqueController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMovimentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimentoResultDto"];
                };
            };
        };
    };
    EstoqueController_minimo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMinimoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaldoItemDto"];
                };
            };
        };
    };
    InternacaoController_list: {
        parameters: {
            query?: {
                status?: "internado" | "alta";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternacaoResumoDto"][];
                };
            };
        };
    };
    InternacaoController_admitir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdmitirDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternacaoResumoDto"];
                };
            };
        };
    };
    InternacaoController_detalhe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternacaoDetalheDto"];
                };
            };
        };
    };
    InternacaoController_prescrever: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrescreverDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoDto"];
                };
            };
        };
    };
    InternacaoController_executar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                execId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutarResultDto"];
                };
            };
        };
    };
    InternacaoController_alta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AltaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternacaoResumoDto"];
                };
            };
        };
    };
    VendasController_list: {
        parameters: {
            query?: {
                status?: "aberto" | "aprovado" | "recusado" | "convertido";
                responsavelId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoResumoDto"][];
                };
            };
        };
    };
    VendasController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrcamentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoResumoDto"];
                };
            };
        };
    };
    VendasController_detalhe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoDetalheDto"];
                };
            };
        };
    };
    VendasController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOrcamentoItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoItemDto"];
                };
            };
        };
    };
    VendasController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                linhaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    VendasController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrcamentoStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrcamentoResumoDto"];
                };
            };
        };
    };
    VendasController_converter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConverterResultDto"];
                };
            };
        };
    };
    ComissoesController_apurar: {
        parameters: {
            query?: {
                /** @description ISO 8601 */
                from?: string;
                /** @description ISO 8601 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApuracaoColaboradorDto"][];
                };
            };
        };
    };
    ComissoesController_minhas: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApuracaoLinhaDto"][];
                };
            };
        };
    };
    ComissoesController_regras: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegraDto"][];
                };
            };
        };
    };
    ComissoesController_upsertRegra: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegraDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegraDto"];
                };
            };
        };
    };
    ComissoesController_removeRegra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    DashboardController_resumo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardDto"];
                };
            };
        };
    };
    InteligenciaController_produtividade: {
        parameters: {
            query?: {
                /** @description ISO 8601 */
                from?: string;
                /** @description ISO 8601 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdutividadeDto"][];
                };
            };
        };
    };
}
